### PR TITLE
Fix crash if no HTTPResponse is set

### PR DESCRIPTION
**Pull request by improbable-andreaskrugersen**
In Unreal it's not guaranteed that the `FHttpResponsePtr` is valid when handling an HTTP request. In the `bConnectedSuccessfully` case it's fine, but otherwise you can crash

### CODE REVIEW

**Comment by improbable-andreaskrugersen** [comment]
Also fixed some more includes in non-Unity builds

**Comment by rweber89** [comment]
Hi @improbable-andreaskrugersen - the 4.27 branch is severely outdated.
I will recommend not merging this in. I'm working on making our various version branches redundant.

I will incorporate your changes into that.

**Comment by rweber89** [comment]
@improbable-andreaskrugersen - Would you mind letting me know what you do to run non-Unity builds? I have not done that before, adding `bUseUnityBuild = false;` on the Target.cs for the project seems to do nothing, and changing the UBT build configuration fails compiling on engine code in 4.27.

**Comment by improbable-andreaskrugersen** [comment]
@rweber89 Setting `bUseUnityBuild = false` is correct but you need to do that in the `Build.cs` file of your module

In regards to the outdated branch: We're still currently upgrading to UE5 but needed an upgrade before that, so the UE4.27 branch was all we could use

**Comment by improbable-andreaskrugersen** [comment]
This is obsolete now. I created a separate PR for include fixes on `dev`

**Pull request closed without merging**
