### PR TITLE
Fix audio sync issue

### PR DESCRIPTION
**Pull request by improbable-andreaskrugersen**
(Second attempt)

This fixes an audio sync issue where the plugin would start to queue empty samples before the audio stream had started playing which can be detected by checking the elapsed variable. The symptom on my end was that the first time I started in editor, sound was in sync. Afterwards it would always have ~15 secs of silence and then be out of sync. Note that we use a custom audio integration (Wwise) but the symptom and fix should be the same for the default one.

Also fixed a memory leak

### CODE REVIEW

**Comment by murillo128** [comment]
wait, i don't think that is the correct license.. should be pointing at

https://github.com/millicast/clas/blob/main/README.md

**Comment by improbable-andreaskrugersen** [comment]
That makes more sense 😄 You probably need to fix your bot first? Do I need to reopen the PR again?

**Comment by murillo128** [comment]
@improbable-andreaskrugersen sorry for getting so long to merge this, could you please sing the CLA so we can merge it?

**Comment by improbable-andreaskrugersen** [comment]
recheck

**Comment by improbable-andreaskrugersen** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by murillo128** [comment]
recheck

**Comment by murillo128** [comment]
Thank you!

**Pull request merged**
